export const PRESETS = [
  {
    id: "midfin360",
    name: "Midfin360",
    tagline: "Trackable App Referrer",
    baseUrl: "https://www.midfin360.com/qr/index.html",
    isReferrerMode: true,
    defaultReferrer: "facebook",
    logoUrl: "/logos/midfin360-logo.png",
    logoName: "Midfin360 (Dark)",
    colorDark: "#000000",
    colorLight: "#FFFFFF",
  },
  {
    id: "midfin360-blue",
    name: "Midfin360 Blue",
    tagline: "Branded Theme",
    baseUrl: "https://www.midfin360.com/qr/index.html",
    isReferrerMode: true,
    defaultReferrer: "campaign",
    logoUrl: "/logos/midfin360-blue.png",
    logoName: "Midfin360 (Blue)",
    colorDark: "#034078",
    colorLight: "#FFFFFF",
  },
  {
    id: "inveztmf",
    name: "InveztMF",
    tagline: "Direct App Link",
    baseUrl: "http://inveztmf.com/app",
    isReferrerMode: false,
    defaultUrl: "http://inveztmf.com/app",
    logoUrl: "/logos/inveztmf-logo.png",
    logoName: "InveztMF Logo",
    colorDark: "#0b192c",
    colorLight: "#FFFFFF",
  },
  {
    id: "custom",
    name: "Custom URL",
    tagline: "Any Destination",
    baseUrl: "https://www.midfin360.com",
    isReferrerMode: false,
    defaultUrl: "https://www.midfin360.com",
    logoUrl: "/logos/midfin360-logo.png",
    logoName: "Midfin360 Logo",
    colorDark: "#000000",
    colorLight: "#FFFFFF",
  },
];

export const LOGO_PRESETS = [
  {
    id: "midfin360",
    name: "Midfin360",
    url: "/logos/midfin360-logo.png",
  },
  {
    id: "midfin360-blue",
    name: "Midfin Blue",
    url: "/logos/midfin360-blue.png",
  },
  {
    id: "inveztmf",
    name: "InveztMF",
    url: "/logos/inveztmf-logo.png",
  },
];
